### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by patrick-brian-mooney** [jedie/DragonPy#8]
Maybe I'm doing something wrong or have failed to set something up, but I haven't yet seen anything obvious. Apologies in advance if I'm missing something.

After a clean install using the PyPI-based bootstrap method, I get the following traceback trying to start DragonPy:

    (DragonPy) 00:41:45 patrick@linawesome bin$ DragonPy 
    Traceback (most recent call last):
      File "/home/patrick/bin/DragonPy/bin/DragonPy", line 7, in <module>
        from dragonpy.core.cli import main
      File "/home/patrick/bin/DragonPy/lib/python3.5/site-packages/dragonpy/core/cli.py", line 39, in <module>
        from dragonpy.CoCo.machine import run_CoCo2b
      File "/home/patrick/bin/DragonPy/lib/python3.5/site-packages/dragonpy/CoCo/machine.py", line 21, in <module>
        from dragonpy.core.gui import DragonTkinterGUI
      File "/home/patrick/bin/DragonPy/lib/python3.5/site-packages/dragonpy/core/gui.py", line 48, in <module>
        from dragonpy.Dragon32.gui_config import RuntimeCfg, BaseTkinterGUIConfig
      File "/home/patrick/bin/DragonPy/lib/python3.5/site-packages/dragonpy/Dragon32/gui_config.py", line 37, in <module>
        class RuntimeCfg(object):
      File "/home/patrick/bin/DragonPy/lib/python3.5/site-packages/dragonpy/Dragon32/gui_config.py", line 53, in RuntimeCfg
        max_delay = CPU.max_delay # maximum time.sleep() value per burst run
    AttributeError: type object 'CPU' has no attribute 'max_delay'

I'm running Python 3.5.2 under x64 Linux Mint 18.3 (an Ubuntu derivative). Would gladly supply any other needed information, if that's helpful.

**Comment by jedie** [comment]
Hm... That's the wrong combination of https://github.com/jedie/DragonPy/ and https://github.com/6809/MC6809 :(

Can you post a `pip freeze` ?!?

**Comment by jedie** [comment]
Ah! The PyPi Packages are not up-to-date... Sorry... Fix is on the way...

**Comment by jedie** [comment]
@patrick-brian-mooney v0.6.0 is now released on PyPi and fixed this.

Thanks for reporting!

I made a fresh virtualenv and test it:
```
$ pip freeze
click==6.7
dragonlib==0.1.7
DragonPyEmulator==0.6.0
MC6809==0.5.0
pkg-resources==0.0.0
Pygments==2.2.0
six==1.11.0
```
I add in README how to create a virtualenv by foot, here: https://github.com/jedie/DragonPy#by-foot

**Comment by patrick-brian-mooney** [comment]
Glad to be helpful! Looks like it's working for me now. Sorry to take so long to get back to you!
